### ISSUE TITLE
Close button or padding (or something) not transitioning on tabs

### ISSUE THREAD

**Issue by aexis-b** [jmcalaway/atom-genesis-ui#2]
I recommend removing the transitions in the tabs, or maybe tweaking them, as when I switch tabs it transitions where the title of the file is, but the close button and the padding before the title of the tab seem to either not be transitioning, or transitioning slower (or faster, something).  I removed the transition altogether and its much cleaner now.

Great scheme!  Nice work man.

**Comment by jeffcalaway** [comment]
Thanks for your input bkwebster!

I've looked into the issue and it appeared that the :before & :after did not have the transition. I've since added the transition and pushed up the patch.

Let me know if there's anything else I can address.
