### ISSUE TITLE
Disable transition

### ISSUE THREAD

**Issue by montogeek** [jmcalaway/atom-genesis-ui#7]
Hi!

Great theme :)

It is possible to disable the animation when you hover a item in the sidebar?

**Comment by montogeek** [comment]
I just disable them, Can we make it a option? I could submit a PR :)

**Comment by cbrst** [comment]
Please do. The transition makes it basically impossible to navigate the tree with the keyboard.

**Comment by jeffcalaway** [comment]
Yep, give me a little bit of time and I'll see to it.

**Comment by montogeek** [comment]
So, you will work on it? I can help :)

**Comment by jeffcalaway** [comment]
The latest update will have the option to turn off the hover effect

**Comment by montogeek** [comment]
Thank you :)
